baseURL = '/'
defaultContentLanguageInSubdir = 'true'
theme = 'monodark'
relativeURLs = 'true'
markup.tableOfContents.endLevel = 4
copyright = "(C) {year} {author}"
enableGitInfo = "true"

[params]
	author = 'i3slkiller'
	mainSections = ["posts"]

[params.mysite]
	copystart = "2023" 


[params.comments]
	enabled = 'true'
	repo = 'i3slkiller/i3slkiller.github.io'

defaultContentLanguage = 'en'
[languages]
	[languages.en]
		contentDir = "content/en"
		languageCode = 'en-us'
		languageName = "English"
		title = "Internet Black Hole"
	[languages.pl]
		contentDir = "content/pl"
		languageCode = 'pl-pl'
		languageName = "Polski"
		title = "Czarna Dziura Internetów"
